FROM pytorch/pytorch:latest
COPY /SASREC /SASRec
# Install Google Cloud SDK
RUN curl -sSL https://sdk.cloud.google.com/ | bash
ENV PATH $PATH:/root/google-cloud-sdk/bin
# Combine pip installations
RUN pip3 install boto3 requests numpy pandas scikit-learn slack-sdk datasets emoji 
RUN pip3 install sentence-transformers gcloud google-cloud google-cloud-secret-manager google-cloud-storage 
RUN pip3 install mlflow tqdm datetime pandas numpy
RUN rm -rf /root/.cache/pip  # Clean pip cache to reduce size
WORKDIR /SASRec


